name: less_worse_more_better
publish_to: none

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  build_static_site:
    path: ../build_static_site

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.0
  #build_web_compilers: ^2.0.0
  #build_vm_compilers: ^1.0.0
  test: ^1.3.0
